# Generated by Django 5.1.4 on 2025-02-02 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grades", "0002_alter_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
