# Generated by Django 5.1.4 on 2025-02-02 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grades", "0003_alter_student_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grade",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
