# Generated by Django 5.1.4 on 2025-02-02 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grades", "0004_alter_grade_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
