# Generated by Django 5.1.4 on 2025-02-02 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grades", "0005_alter_assignment_id_alter_enrollment_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
