# Generated by Django 5.1.4 on 2025-02-02 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grades", "0006_alter_teacher_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
